### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by mvdan** [corbinlc/GNURootDebian#1]
Hello, I come from F-Droid. Someone [asked for your app to be included](https://gitlab.com/fdroid/fdroiddata/issues/267) so I went to have a look at it.

We can't include it until we can build the app from source:

* There are prebuilt native binaries in `libs/armeabi-v7a/`
* `project.properties` references libraries which are outside of the repo source tree

That last point can be solved by either checking in said libraries or by switching to Gradle and using maven dependencies. The latter is easier to set up and better in the long run.

Also, remove `bin/` and `gen/` from the repo, they're output dirs.

Cheers!

**Comment by jasonspiro** [comment]
Hi!  Thanks for your quick response.

[libs/armeabi-v7a/](https://github.com/corbinlc/GNURootDebian/tree/master/libs/armeabi-v7a) doesn't actually contain any binaries at all.

[libs/armeabi-v7a/libarch-supported.so](https://github.com/corbinlc/GNURootDebian/blob/master/libs/armeabi-v7a/libarch-supported.so) looks like it's a binary file, but it's actually just text.

As for the rest -- I can't answer.  Corbin maintains this, not me.  :)

**Comment by corbinlc** [comment]
Oh good.  Someone is trying to build this from scratch.  I need to do this myself.  I will do it soon and will update the repo with any missing files and all instructions needed.  The missing libraries are probably from the Terminal Emulator for Android.  The libs are actually just text files.

**Comment by mvdan** [comment]
Why would someone have a .so native binary that is just a text file? That doesn't make any sense at all.

**Comment by corbinlc** [comment]
The "someone" is me and there is a reason.  

http://developer.android.com/google/play/filters.html
See "Publishing Multiple APKs with Different Filters"
See specifically "CPU Architecture (ABI)" bullet point.

If you want to release a APK but force it to be only available for a particular architecture, then you include something (doesn't actually have to be an ELF) in the appropriate libs directory.  The only devices that support that architecture will receive that APK version.

When I build, the libs directory (which is a link) is updated to point at the correct libs directory (armhf, armel or x86) such that the build only supports one architecture.  The reason for doing this, is the extension file (.obb) and assets contain ELFs.  

So each APK is coupled with the correct architecture dependent assets and extension files and then the text file in the correct libs directory forces that APK to be received by the correct devices via the Play Store.  

I didn't see another documented way to make sure an APK version is only received by devices with the correct CPU architecture.  Maybe there is a better way?

**Comment by mvdan** [comment]
Fair enough.

**Comment by jasonspiro** [comment]
Let me add:  The "Terminal Emulator for Android" mentioned above is available from:

https://github.com/jackpal/Android-Terminal-Emulator

**Comment by jpfox** [comment]
@mvdan why GNURootDebian is not on F-Droid ?
I see you started to do necessary job to add it but it is not in F-Droid repos. Is there any reason I have not found ?
Thanks for your reply.

**Comment by mvdan** [comment]
Pretty much just lack of time.

**Comment by davidhedlund** [comment]
@corbinlc 
1) Have you documented how to build GNURootDebian?


2) I'm want to submitt your app to the new F-Droid forum, can you please this?:
> * [ ] The app complies with the [inclusion citeria](https://f-droid.org/wiki/page/Inclusion_Policy)
> * [ ] The original app author has been notified (and supports the inclusion).
