### ISSUE TITLE
can't git clone in /sdcard/; link fails and removes file

### ISSUE THREAD

**Issue by innolee** [corbinlc/GNURootDebian#104]
I am running into a problem that I would like some advice on.  I want to have a git repository in my /sdcard/ folder so that I can access the files from other android applications.  Git clone works fine in /root/, but fails as seen below in /sdcard/:

```
root@localhost:/sdcard# git clone ssh://user@host/directory/repository folder
Cloning into 'folder'...
user@host's password:
remote: Counting objects: 37413, done
remote: Compressing objects: 100% (11833/11833), done
remote: Total 37413 (delta 22948), reused 2864
 .....
error: unable to write sha1 filename /sdcard/folder/.git/objects/pack/pack-1ab2...889.pack: No such file or directory
fatal: cannot store pack file
fatal: index-pack failed
```

Looking into it, it appears to be a problem with ln and/or proot. Creating a link not only fails, but also removes the target file::

```
root@localhost:/sdcard/test# echo asdf > foo
root@localhost:/sdcard/test# ln foo bar
ln: failed to create hard link 'bar' => 'foo': Operation not permitted
root@localhost:/sdcard/test# ls -a
. ..
root@localhost:/sdcard/test#
```

Before the most recent (23 Aug) GNURoot Debian update through the play store it had a slightly different behavior, leaving behind a .proot\* file:

```
root@localhost:/sdcard/test# ls -a
. .. .proot.l2s.foo0001.0002
root@localhost:/sdcard/test# cat proot*
asdf
```

When I try the same inside /root, it works as expected.  Is this a known issue?  If linking will not work, then a better error message or at least not removing the file seems preferable to the current behavior.

Thanks.

**Comment by recri** [comment]
You might try formatting the sd card with a native Linux file system, since they support links and owners and modes and all the other things that git might be expecting.  The DOS FAT file systems that come by default on sd cards don't support much.

**Comment by tigran123** [comment]
@recri The hard links don't work on the internal flash either (see issue #114 ) _after_ doing `apt update && apt upgrade`.

**Comment by corbinlc** [comment]
I have released a new beta version. You sign up for the beta program here: https://play.google.com/apps/testing/com.gnuroot.debian
This version makes it so you can delete old failed git clone directories and makes it so git clone in most cases will work in the /home directory or on the sdcard (or emulated sdcard). Cases that still won't work is the home directory and all of the sdcard is formatted as FAT and so you cannot have two files with the same name, but different cases.
In the future the home directory will be moving to internal storage.
Please try out the beta version and tell me how it goes.

**Comment by corbinlc** [comment]
I am closing this as I pushed this release to production and feedback has been good so far. If issues remain or if a new issue has popped up, please file a new issue.
