### ISSUE TITLE
Git clone causes wierd filesystem issue

### ISSUE THREAD

**Issue by ddade** [corbinlc/GNURootDebian#105]
Apologies for not being able to provide a SSCCE (proprietary code), but trying to clone a project for the first time errors out.

I can manually create with the touch command and then delete the file it is complaining about.

The created pack directory is reported to have 0 files, but even root cannot delete it because the directory is reported to not be empty, andnit must be deleted from outside GNURoot Debian:

localhost:~ $ git clone ssh://myserver.com:42/~/ads.git
Cloning into 'ads'...
ddade@myserver.com's password:
remote: Counting objects: 8157, done.
remote: Compressing objects: 100% (7110/7110), done.
remote: Total 8157 (delta 4126), reused 3477 (delta 903)
Receiving objects: 100% (8157/8157), 151.54 MiB | 8.59 MiB/s, done.
Resolving deltas: 100% (4126/4126), done.
error: unable to write sha1 filename /home/ddade/ads/.git/objects/pack/pack-8f68056b087796415f11e6bca0f2d3ea55702e97.pack: No such file or directory
fatal: cannot store pack file
fatal: index-pack failed
localhost:~ $ ls -la ads/.git/objects/pack
total 24
drwxrwx---. 2 root 9997 4096 Sep 11 17:32 .
drwxrwx---. 4 root 9997 4096 Sep 11 17:31 ..
localhost:~ $ rmdir ads/.git/objects/pack
rmdir: failed to remove 'ads/.git/objects/pack': Directory not empty
localhost:~ $ touch ads/.git/objects/pack/pack-8b8caf4e4d9b5f5e6f173bd395a036412ef09c9f.pack
localhost:~ $ ls -la ads/.git/objects/pack                                           total 32
drwxrwx---. 2 root 9997 4096 Sep 11 17:35 .
drwxrwx---. 4 root 9997 4096 Sep 11 17:31 ..
-rw-rw----. 1 root 9997    0 Sep 11 17:35 pack-8b8caf4e4d9b5f5e6f173bd395a036412ef09c9f.pack
localhost:~ $ rm ads/.git/objects/pack/pack-8b8caf4e4d9b5f5e6f173bd395a036412ef09c9f.pack
localhost:~ $

Thanks for an awesome project; having to root all my devices is not always convenient.

**Comment by ddade** [comment]
More info: Nexus 9 Tablet running Nougut, which don't have sdcards.

**Comment by Atemu** [comment]
I also have this problem on my unrooted Oneplus one. I have tried every way I found in the web but I can't delete folders created by git

**Comment by ddade** [comment]
@Atemu I was able to delete them by using FileExplorer to delete them out of the GNURoot directory where it created my home directory.

**Comment by ddade** [comment]
Can we get some type of acknowledgement from the dev(s) that they've at least seen this bug report?

**Comment by muehlber** [comment]
This problem persists for about two months now and I'm wondering if GNURoot Debian is still maintained?

Do the other GNURoot* have the same issue? Is it even related to GNURoot Debian or more an issue of git or some Linux library?

**Comment by tomaklutfu** [comment]
I think this is a `proot` issue that gives wrong priviledges to files. I cannot even delete those files within app and it also causes `pip3` to fail. I think we need to ping `proot` developer in this repo or may be replace `proot` implemented here with previous version that worked in the app.

**Comment by jeiksegovia** [comment]
It's because the write privilege on the home directory has problems when git creates files.
If you git clone on /tmp,  it should work.

If any one knows how to change the home directory to other location I will appreciate the help. 

Thanks

**Comment by tomaklutfu** [comment]
I know how to change `/home` and I do change it but the problem still exist for files that `git` creates and starts with `.` character or for files within `.git` folders. You can change `home` in `/support/launchProot` by copying the file to `/sdcard`, editing, and copying back to `/support`.

Thanks,

**Comment by jeiksegovia** [comment]
Hoo thanks!!.
I Installed the last version of gnuroot debian. I had not any old previous  version. And install and patch. 
What I have done in order to clone is this:
Install git 
Install git-build-essential
Git clone to the tmp file director.
I had no errors. 
I was Experimenting this error "unable to write sha1  filename". And some .file inside the objects/pack was not detected by the system.

**Comment by muehlber** [comment]
Cloning repositories in /tmp is indeed a temporary workaround. At least I can push and pull and commit.

Interesting observations: git operations fail after moving (mv /tmp/old_repo /tmp/new_repo) a repository and removing a repository (rm -rf /tmp/new_repo) fails with "Operation not permitted" for some files in /tmp/new_repo/.git ; I can't even ls/chown/chmod those files.

I'm really wondering if some future version of GNURootDebian will allow me to clean this up again.

**Comment by tomaklutfu** [comment]
As I said before I believe it is `proot` to blame for this. It used to work before last update. It may be because there is a new flag that hides `proot` specific files.

**Comment by corbinlc** [comment]
The last version of proot added better emulation of having multiple users.  To make this happen, it creates "hidden" files which contain the faked out owner/group/rwx etc for each file  There must be something going wrong with this.  I will have to debug a little to figure out the corner case where this is going wrong.  I haven't repeated this issue yet.  Can someone provide the commands needed starting from a fresh GNURoot Debian install to run into the issue?  Please only use a public repo to demonstrate your issue.  Also, please provide the same, but working commands where you clone to the /tmp directory.  I am pretty sure I understand what you are all doing, but the specific examples will make sure.

**Comment by jeiksegovia** [comment]
Apt-get update 
Install git as usual, using apt get. 
Then, clone any repository on /home directory. 
You should see some warnings.

**Comment by ddade** [comment]
That is exactly what I did as well, that provoked the problem.

Thanks for looking in to this,

Donald

**Comment by narigondelsiglo** [comment]
Waiting for the real solution :)

**Comment by Atemu** [comment]
The proot meta files can sometimes glitch out and not delete properly, thus blocking a dir from getting deleted (noticable in git for example).

do

`nano /support/execInProot`

\^W for ` -H` and remove it. Then \^O \^X and in every new window it'll now show the meta files.

If you navigate to the .git dir you should see a meta file that exist there for some reason and you can do with it whatever you want.

Git should then work properly again but other stuff might break because there are suddenly files in directories that shouldn't be there, so I'd suggest you to add the ` -H` to the command (it was behind ` -v` originally) again if you don't need to see the meta files.

**Comment by muehlber** [comment]
@narigondelsiglo: The real solution seems to be to switch to "Termux".

**Comment by narigondelsiglo** [comment]
@muehlber already tried termux, it's incomplete for my needs... I like to have the full stack of packages. Anyway this is getting beyond the topic so leave it here...
I would like this software to get mature and fail proof.
Great job @corbinlc! 
Thank you

**Comment by Breta01** [comment]
I also have this issue. I'm on android 7.1 and I get the "error: unable to write sha1 filename ..." whenever I try git clone in `/home` directory. On clean installation I run these commands:
```
apt-get update
apt-get upgrade
apt-get install git
cd /home
git clone https://github.com/Breta01/dotfiles.git
```

It failed for all repos that I tried so far.
When I follow @Atemu instructions and edit `/support/execInProot` file. Then I was able to delete .git folder, but `git clone` still doesn't work.

It would be really great if someone could solve this. I'm willing to help or at least test the solution.

**Comment by narigondelsiglo** [comment]
Maybe put an issue on https://github.com/proot-me/PRoot/issues ?
I don't know if it's right to continue this here... guess it has something to do with proot, isn't it?

**Comment by corbinlc** [comment]
I have released a new beta version.  You sign up for the beta program here:  https://play.google.com/apps/testing/com.gnuroot.debian
This version makes it so you can delete old failed _git clone_ directories and makes it so git clone in most cases will work in the /home directory or on the sdcard (or emulated sdcard).  Cases that still won't work is the home directory and all of the sdcard is formatted as FAT and so you cannot have two files with the same name, but different cases.
In the future the home directory will be moving to internal storage.

**Comment by corbinlc** [comment]
Please try out the beta version.  It may take an hour or two for the new version 0.6.8 to show up for all beta members as being available.  Please tell me how that goes for you.

**Comment by Breta01** [comment]
Great! I just tested the 0.6.8 version on my Pixel C tablet (Android 7.1) and the git clone works for me in `/home` directory. Do you want some more detailed testing?

**Comment by corbinlc** [comment]
Nothing particular.  I have already tested it some related to the desired change.  Just use the app normally and see if there is something weird that pops up.  This change is very focused, so it is unlikely to break anything new, but you never know.

**Comment by narigondelsiglo** [comment]
Great job!!!

**Comment by corbinlc** [comment]
I am closing this as I pushed this release to production and feedback has been good so far.  If issues remain or if a new issue has popped up, please file a new issue.
