### ISSUE TITLE
Getting the source code which makes "proot -n" work

### ISSUE THREAD

**Issue by jasonspiro** [corbinlc/GNURootDebian#11]
Hi again!

I'm using GNURoot Debian 0.2.6_armhf on a Samsung Galaxy S Relay 4G running Android 4.1.2.

On my phone, when I launch `/data/data/com.gnuroot.debian/support/proot`, I see a help message which lists PRoot's various options.

One of these options is:

    -n    Shadow files contents to live on the '.proot.noexec' binding
          except when currently being executed, open or memory mapped.

I assume that this `-n` option is an extension to PRoot, and that it's only available in the version of PRoot which you ship with GNURoot Debian.

Where can I find the source code which makes `proot -n` work?

Thanks!

**Comment by corbinlc** [comment]
Sorry.  I was out last week.  Looks like I haven't posted this source code yet.  My next task is to make sure I can build everything from scratch from the repository (and do some cleanup of the repository...it is a mess right now).  I will make sure the correct PRoot source code is up there.  

I just got back from vacation, so I have other things I need to do (not related to this project), but I should get this done this week and then things should be good going forward.

**Comment by corbinlc** [comment]
Not forgotten.  Just had very little time last week.  That being said, I am well on my way to moving to Android Studio and cleaning up the repository as a whole and using submodules etc to make everything nice for you and others.

**Comment by jasonspiro** [comment]
OK.  Thanks for the status update.

Note that, for project maintainers such as you, Git submodules may be a usability nightmare.  See, for example, [this article](http://somethingsinistral.net/blog/git-submodules-are-probably-not-the-answer/#doing-it-wrong) by Adrien Thebo. In a different article, Christophe Porteneuve summarizes the potential pitfalls:

> * Every time you add a submodule, change its remote’s URL, or change the referenced commit for it, you demand a manual update by every collaborator.
> * Forgetting this explicit update can result in silent regressions of the submodule’s referenced commit.
> * Commands such as `status` and `diff` display precious little info about submodules by default.
> * Because lifecycles are separate, updating a submodule inside its container project requires two commits and two pushes.
> * Submodule heads are generally detached, so any local update requires various preparatory actions to avoid creating a lost commit.
> * Removing a submodule requires several commands and tweaks, some of which are manual and unassisted.

There are other options other than the use of submodules.  I have no experience with any of them, so I don't know what to recommend.

**Comment by corbinlc** [comment]
https://github.com/corbinlc/GNURootDebian/tree/master/GNURootDebianSource/src/main/build_rootfs/PRoot/src/extension/noexec_shadow

**Comment by jasonspiro** [comment]
Cool, thank you very much!

Closing.
