### ISSUE TITLE
Nov 30th patch, creates two application 

### ISSUE THREAD

**Issue by Root-voidX** [corbinlc/GNURootDebian#121]
After the update. There is two gnuroot debian apps.  Only one works while the other crashes. Please look into it!

**Comment by corbinlc** [comment]
I just updated the app to fix this.  Can you try today's version and tell me how it goes?

**Comment by Root-voidX** [comment]
It's not on the Playstore yet, when it is ill try it !

**Comment by corbinlc** [comment]
Sorry.  Google sent me an notification that the new version was live in the play store, so I thought I could tell people about it.  Maybe check again in a couple of hours.  Btw... the play store app seems to cache stuff and sometime takes a while to see new version even when they are out (while the website shows them sooner).  I am not sure how to force it to update, but waiting is probably fine.

**Comment by Root-voidX** [comment]
Okay so if I search the app again I can see an update. Installed. Yes the second icon is gone!!! Yes you you boot into bash by default. All my packages seem to be intact!

**Comment by corbinlc** [comment]
Ok great!  Sorry for the problems with the previous update.  I am going to close this issue, but please continue to file issues you see via github.  Also, if you reported this issue via email or play store review as well, please update the email thread or review, so I know who has been made happy and who is still looking for problem resolution.  Thanks!

**Comment by corbinlc** [comment]
Oh, by the way, you said "All my packages seem to be intact".  Did the previous version mess up the packages you already had setup?  I haven't heard that, but I did see someone mention they spent hours getting back to a working environment.

**Comment by Root-voidX** [comment]
Yes, the previous version wiped all my packages. It forced a reinstall of the whole p-root and xterm and I had to reinstall my DE, octave and other softwares

**Comment by corbinlc** [comment]
that is a big deal.  can you file a separate issue for that?

**Comment by Root-voidX** [comment]
Yup I have opened a new issue
