### ISSUE TITLE
Bash doesn't start automatically

### ISSUE THREAD

**Issue by Atemu** [corbinlc/GNURootDebian#123]
Whenever you open a new window (including window 1) you can't use bash features such as arrow up or Tab.

**Comment by tomtom** [comment]
It seems the default shell setting is ignored after the last update and always sh is used. I have to run bash from the sh command line.

**Comment by corbinlc** [comment]
I just released an update which should fix this.  Can you try in and tell me how it goes?

**Comment by Atemu** [comment]
Fixed for me so far, I'll update this if the bug comes back. Ty!
