### ISSUE TITLE
up/down arrow keys don't cycle thru previous commands

### ISSUE THREAD

**Issue by drhuffman12** [corbinlc/GNURootDebian#126]
Confirmed w/ hacker keyboard and ZenUI on Asus ZenFone 2.

With Hacker, escape codes are added to the screen.

With ZenUI, the cursor leaves the current command line row [up jumps to top row; down moves down row[s]].

**Comment by drhuffman12** [comment]
Also [related?], tab key adds a tab to command line text; it does not auto-complete.

**Comment by corbinlc** [comment]
I just updated the app to restore using /bin/bash and the default command when launching a term.  This should fix the stated issue.  Please tell me how it works for you.

**Comment by drhuffman12** [comment]
Arrow and tab keys work again. Thanks! :)

**Comment by corbinlc** [comment]
No problem.  Sorry we botched a few things this time around.
