### ISSUE TITLE
start xfce4

### ISSUE THREAD

**Issue by philrob** [corbinlc/GNURootDebian#131]
Hi, I'm a newbie to GNURoot Debian and learning Linux. Installed GNURoot Debian on my Nexus 7 (2013) and then used apt-get to install xfce4 which seemed to go OK. How do I actually start it? Have tried startxfce4 (Window 1) but command not recognised. I'm trying to use it with XSDL which I've also installed from Google Play. Sorry if this is a very basic question. Regards Phil

**Comment by Root-voidX** [comment]
I can't get xsdl working in regards to issue # 127

But you can use xterm and type in startxcfe if you like. I use LXDE instead but steps are the same

**Comment by Root-voidX** [comment]
I meant issue #127 oops

**Comment by philrob** [comment]
Hi,
Re-ran apt-get install xfce4 and now startxfce4 command is there! - no idea what's different.
HOWEVER, still not sure what to do as running startxfce4 is reporting errors ... need to diagnose more .... and report back.

**Comment by philrob** [comment]
I think GNUROOT Debian updated between me doing the first and second attempt at apt-get install xfce4 or I missed an error on the first attempt. I am going to completely reinstall GNUROOT Debian from scratch and run apt-get update && apt-get upgrade then press the button for Xterm which initially does further installs to run the X Terminal followed again by apt-get update/upgrade. Then I am going to have a good look at how it works in particular some of the scripts in /support. Cheers Phil
