### ISSUE TITLE
NOT an issue. Just 2 questions.

### ISSUE THREAD

**Issue by CraftedCube** [corbinlc/GNURootDebian#16]
Okay I've used a lot of ways to get Debian on my android with full desktop, and most of them didn't work, and the closest I got was a full desktop but it was slow.

This one looks promising!
So here are the questions.

May I see some screenshots of the app AND desktop? I don't see any on Google Play.

Can I put and run all of the apps memory on my micro as card? (Like the image file and still run it)

**Comment by corbinlc** [comment]
> May I see some screenshots of the app AND desktop? I don't see any on Google Play.
Built in support for a graphical desktop will be added fairly soon.  I will add screen shots then.  Right now, you either need to install a vncserver and launch and connect to that, after installing your favorite desktop environment (I am going to default to xfce). Alternatively, you can install the desktop environment and use this in conjunction with the Xsdl server (found in the play store).

> Can I put and run all of the apps memory on my micro as card? (Like the image file and still run it)
Not really.  I have something that works for some devices/android versions but is slow.  I am going to do more work here to make it work universally (I hope) and faster (should be easier).
The reason it doesn't "just work" is that the sdcard is mounted as a FAT partition with the noexec flag set.
