### ISSUE TITLE
How to install GNURootWheezy as a system app?

### ISSUE THREAD

**Issue by SeaDude** [corbinlc/GNURootDebian#186]
I have an Nexus 7 (2013) tablet with a non-Google Apps version of GNURootWheezy installed (which is awesome!) however, I am unable to visit many folders on the tablet due to "permission denied". 

The device is rooted with SU and TWRP recovery, but the GRW terminal will not allow me to visit the root filesystem. From my reading, this is due to WHERE GRW is installed (/system app vs. /data(?) app).

Does anyone have insights into the best place in the Android filesystem to install GRW?
How is this accomplished? 

Thanks

**Comment by pzi123** [comment]
rooting itself does not do anything until you change the proot call to be run with root permissions. I wrapped the proot call in /support/execInProot in /system/xbin/su -c "...". The patch is below. This also enables access to /dev directory so things like ssh-agent etc can get to /dev/random - and many more benefits. Unfortunately this works only in android 5. The new SuperSU in android 6 with split tree does not work.  Maybe somebody else has a fix for it in 6 for gnuroot.

```
root@localhost:/support# diff -c execInProot- execInProot
*** execInProot-        Wed May 24 16:00:15 2017
--- execInProot Wed May 24 19:55:18 2017
***************
*** 3,17 ****
  /data/data/com.gnuroot.debian/support/busybox clear

  blue='\033[0;34m'; NC='\033[0m';
- echo ""
- echo -e "${blue}Sponsored by: "
- echo "                                          "
- echo " _____                   _                "
- echo "|_   _| ___  ___  ___  _| | _ _  ___  ___ "
- echo "  | |  | -_||  _|| . || . || | ||   || -_|"
- echo "  |_|  |___||_|  |__,||___||_  ||_|_||___|"
- echo "                           |___|          "
  echo -e "${NC}"

  #launch PRoot
! PROOT_TMP_DIR=/data/data/com.gnuroot.debian/support/ /data/data/com.gnuroot.debian/support/proot -r /data/data/com.gnuroot.debian/debian -v -1 -p -H -0 -l -L -b /sys -b /dev -b /proc -b /data -b /mnt -b /proc/mounts:/etc/mtab -b /:/host-rootfs -b /storage/emulated/0/GNURoot/intents:/intents -b /storage/emulated/0/GNURoot/home:/home -b /storage/emulated/0:/sdcard -b /data/data/com.gnuroot.debian/support/:/support -b /data/data/com.gnuroot.debian/support/ld.so.preload:/etc/ld.so.preload  $@
--- 3,10 ----
  /data/data/com.gnuroot.debian/support/busybox clear

  blue='\033[0;34m'; NC='\033[0m';
  echo -e "${NC}"

  #launch PRoot
! /system/xbin/su -c "HOME=/root PROOT_TMP_DIR=/data/data/com.gnuroot.debian/support/ /data/data/com.gnuroot.debian/support/proot -r /data/data/com.gnuroot.debian/debian -v -1 -p -H -0 -l -L -b /sys -b /dev -b /proc -b /data -b /mnt -b /proc/mounts:/etc/mtab -b /:/host-rootfs -b /storage/emulated/0/GNURoot/intents:/intents -b /storage/emulated/0/GNURoot/home:/home -b /storage/emulated/0:/sdcard -b /data/data/com.gnuroot.debian/support/:/support -b /data/data/com.gnuroot.debian/support/ld.so.preload:/etc/ld.so.preload  $@"
!
```

**Comment by SeaDude** [comment]
Thanks for the response. How is this patch implemented? Is it already present in the latest source download or something I need to edit my end?

**Comment by pzi123** [comment]
The gnuroot is advertised as 'no rooting' required so there is no 'su' called to get the proot fully functional. To add this just edit the /support/execInProot script and add the changes from the diff I sent.

**Comment by SeaDude** [comment]
Hm. My new execInProot file looks like this: 
`/data/data/com.gnuroot.debian/support/busybox clear

blue='\033[0;34m'; NC='\033[0m';
echo "" 
echo -e "${blue}Sponsored by: "
echo "                                          "
echo " _____                   _                "
echo "|_   _| ___  ___  ___  _| | _ _  ___  ___ "
echo "  | |  | -_||  _|| . || . || | ||   || -_|"
echo "  |_|  |___||_|  |__,||___||_  ||_|_||___|"
echo "                           |___|          "
echo -e "${NC}"

#launch PRoot
/system/xbin/su -c "HOME=/root PROOT_TMP_DIR=/data/data/com.gnuroot.debian/support/ /data/data/com.gnuroot.debian/support/proot -r /data/data/com.gnuroot.debian/debian -v -1 -p -H -0 -l -L -b /sys -b /dev -b /proc -b /data -b /mnt -b /proc/mounts:/etc/mtab -b /:/host-rootfs -b /storage/emulated/0/GNURoot/intents:/intents -b /storage/emulated/0/GNURoot/home:/home -b /storage/emulated/0:/sdcard -b /data/data/com.gnuroot.debian/support/:/support -b /data/data/com.gnuroot.debian/support/ld.so.preload:/etc/ld.so.preload  $@"`

After rebooting, GNURootDebian just flashes when I click the icon. The program doesn't launch on my device. 

Did I miss something?

**Comment by pzi123** [comment]
looks like you lost the first line with #! and have some back quotes in wrong places. Mine looks like this:

```
root@localhost:/support# cat execInProot
#!/data/data/com.gnuroot.debian/support/busybox sh

/data/data/com.gnuroot.debian/support/busybox clear

blue='\033[0;34m'; NC='\033[0m';
echo -e "${NC}"

#launch PRoot
/system/xbin/su -c "HOME=/root PROOT_TMP_DIR=/data/data/com.gnuroot.debian/support/ /data/data/com.gnuroot.debian/support/proot -r /data/data/com.gnuroot.debian/debian -v -1 -p -H -0 -l -L -b /sys -b /dev -b /proc -b /data -b /mnt -b /proc/mounts:/etc/mtab -b /:/host-rootfs -b /storage/emulated/0/GNURoot/intents:/intents -b /storage/emulated/0/GNURoot/home:/home -b /storage/emulated/0:/sdcard -b /data/data/com.gnuroot.debian/support/:/support -b /data/data/com.gnuroot.debian/support/ld.so.preload:/etc/ld.so.preload  $@"

```

**Comment by SeaDude** [comment]
I took the build all the way down to bare bones again and reinstalled EVERYTHING. 
GNURootDebian installs just fine, but when I erase the default `execInProot` file and replace it with your patch: 
    #!/data/data/com.gnuroot.debian/support/busybox sh

    /data/data/com.gnuroot.debian/support/busybox clear

    blue='\033[0;34m'; NC='\033[0m';
    echo -e "${NC}"

    #launch PRoot
    /system/xbin/su -c "HOME=/root PROOT_TMP_DIR=/data/data/com.gnuroot.debian/support/ /data/data/com.gnuroot.debian/support/proot -r /data/data/com.gnuroot.debian/debian -v -1 -p -H -0 -l -L -b /sys -b /dev -b /proc -b /data -b /mnt -b /proc/mounts:/etc/mtab -b /:/host-rootfs -b /storage/emulated/0/GNURoot/intents:/intents -b /storage/emulated/0/GNURoot/home:/home -b /storage/emulated/0:/sdcard -b /data/data/com.gnuroot.debian/support/:/support -b /data/data/com.gnuroot.debian/support/ld.so.preload:/etc/ld.so.preload  $@"

GnuRootDebian just flashes when I click the icon. If I keep clicking the icon I can barely see the message. Only thing I can make out is `permission denied`. I know you said "this works only in android **5**." I'm working with Android **5.1.1**. 

Is this the issue? Do I need to build with 5.0? 

Thanks for your assistance on all of this.

**Comment by pzi123** [comment]
Is it possible that you don't have you system rooted? Do you have SuperSU installed and the /system/xbin/su present?

**Comment by SeaDude** [comment]
Yes, SuperSU is installed and in `system/xbin/su`. 

    user5@system:~$ adb shell
    shell@grouper:/ $ su
    root@grouper:/ # cd /system/xbin/ && ls                                        
    daemonsu
    dexdump
    su
    supolicy
root@grouper:/system/xbin #

**Comment by SeaDude** [comment]
If it matters, I install SuperSU a little differently than most because I do so without wifi...

From laptop: `adb push UPDATE-SuperSU-v2.82-20170528234214.zip /sdcard/Android/data` then boot to TWRP recovery
Click "Install"
Navigate to `Android/data`
Select SuperSU .zip file
Reboot system
Click the SuperSu icon, tap start DONE

**Comment by SeaDude** [comment]
If this helps at all, here are the (EXTENSIVE!) steps I follow to install GNURootDebian outside of the gp store: 
Install GNURootDebian

1. Boot tablet to Android
2. Open terminal on laptop =cd= to the directory where the GNURootDebian.apk file resides 
3. =adb shell=
4. =su= then acknowledge (click Grant) on the tablet
5. =adb devices= to be sure the device is being read
6. =adb install GNURootDebianSource-armhf-release.apk=
7. =cd /sdcard/Android/obb=
8. =mkdir com.gnuroot.debian= 
9. =exit= to exit root, =exit= to exit adb shell
10. Copy =main.10.com.gnuroot.debian.obb= to this directory
11. =adb push main.10.com.gnuroot.debian.obb /sdcard/Android/obb/com.gnuroot.debian=
12. Takes ~2-3 mins!
13. =adb reboot=
14. Open the tablet and click GNURootDebian icon. App will install, but will not yet have root privs
15. Takes ~3-5 mins to install GNURootDebian
16. Give GNURootDebian root permissions
17. You need to edit the file =execInProot= which resides in =/data/data/com.gnuroot.debian/support=. There is probably a better way, but here is how I did it. 
18. Boot to Recovery Mode
19. Click Advanced, File Manager
20. Navigate to =/data/data/com.gnuroot.debian/support/execInProot= and tap Delete. Swipe to confirm
21. Create and save a text file on your laptop called =execInProot= and paste in this patch code
22. #!/data/data/com.gnuroot.debian/support/busybox sh
23. 
24. /data/data/com.gnuroot.debian/support/busybox clear
25. 
26. blue='\033[0;34m'; NC='\033[0m';
27. echo -e "${NC}"
28. 
29. #launch PRoot
30. /system/xbin/su -c "HOME=/root PROOT_TMP_DIR=/data/data/com.gnuroot.debian/support/ /data/data/com.gnuroot.debian/support/proot -r /data/data/com.gnuroot.debian/debian -v -1 -p -H -0 -l -L -b /sys -b /dev -b /proc -b /data -b /mnt -b /proc/mounts:/etc/mtab -b /:/host-rootfs -b /storage/emulated/0/GNURoot/intents:/intents -b /storage/emulated/0/GNURoot/home:/home -b /storage/emulated/0:/sdcard -b /data/data/com.gnuroot.debian/support/:/support -b /data/data/com.gnuroot.debian/support/ld.so.preload:/etc/ld.so.preload  $@"
31. =adb push execInProot /data/data/com.gnuroot.debian/support/=
32. =adb reboot=

**Comment by pzi123** [comment]
I did the change to the execInProot in a different way. I installed the gnurootDebian straight from my tablet using playstore.  After that in a terminal session on the tablet I installed the vim and edited the /support/execInProot directly.  You have the write permission in /support right from the start.

```
# apt-get update
# apt-get install vim
# vim /support/execInProot
```

**Comment by SeaDude** [comment]
Alright, cool. I'll try that

**Comment by SeaDude** [comment]
["Finally its happened to me..."](https://www.youtube.com/watch?v=xk8mm1Qmt-Y)

Thanks a lot @pzi123 

Here are the steps I took for anyone else needing them: 

* Long hold on GRD icon, drag to uninstall
* `adb pull` both `packages.list` and `packages.xml` and search for `gnu*` no results
* Mount the `/system` partition using `mount -o rw,remount,rw /system`
* `mkdir /sdcard/Android/obb/com.gnuroot.debian` for the .obb file
* `adb install GNURootDebianSource-armhf-release.apk` . Installs with "success"
* `adb push main.10.com.gnuroot.debian.obb /sdcard/Android/obb/com.gnuroot.debian` This is for non-Google Play setups like mine
* `adb reboot` just for house keeping
* unable to edit `execInProot` at this point because GRD has not installed yet so the file does not exist
* click the GRD icon to install. Works great. 
* `apt-get update`
* `apt-get install nano` . nano installs just fine
* `nano /support/execInProot`
* Remove: Everything in execInProot file
* Add (by hand!): 
`#!/data/data/com.gnuroot.debian/support/busybox sh

/data/data/com.gnuroot.debian/support/busybox clear

blue='\033[0;34m'; NC='\033[0m';
echo -e "${NC}"

#launch PRoot
/system/xbin/su -c "HOME=/root PROOT_TMP_DIR=/data/data/com.gnuroot.debian/support/ /data/data/com.gnuroot.debian/support/proot -r /data/data/com.gnuroot.debian/debian -v -1 -p -H -0 -l -L -b /sys -b /dev -b /proc -b /data -b /mnt -b /proc/mounts:/etc/mtab -b /:/host-rootfs -b /storage/emulated/0/GNURoot/intents:/intents -b /storage/emulated/0/GNURoot/home:/home -b /storage/emulated/0:/sdcard -b /data/data/com.gnuroot.debian/support/:/support -b /data/data/com.gnuroot.debian/support/ld.so.preload:/etc/ld.so.preload  $@"``
* CTRL+X, then RET to save
* `exit`
* `adb reboot` in laptop terminal
* Click on GRD icon...I get the Superuser Request from SuperSU...click Grant
* GRD has been granted root access!! 

BINGO!!
