### ISSUE TITLE
For GNURoot Debian, should we be using this issue tracker or the other GNURoot issue tracker?

### ISSUE THREAD

**Issue by jasonspiro** [corbinlc/GNURootDebian#2]
Hi!

I just have a question.

Which is the correct issue tracker to use for issues with [GNURoot Debian](//play.google.com/store/apps/details?id=com.gnuroot.debian)?  Should we use the [gnuroot tracker](//github.com/corbinlc/gnuroot/issues), or the [GNURootDebian tracker](//github.com/corbinlc/GNURootDebian/issues)?

I'm using GNURoot Debian 0.2.0_armhf on a Samsung Galaxy S Relay with Android 4.1.2.

P.S.  Thank you very much for writing and maintaining GNURoot!

**Comment by corbinlc** [comment]
Users of GNURoot Debian should use this issue tracker.  GNURoot as it was will be phased out in favor of this.  GNURoot Wheezy and GNURoot WheezyX are going away first after a couple additional changes, as this will be superior to those.  I am not sure how I want to continue support for other Linux Distros and which distros to support.  Might create a version where you can just provide your own rootfs to support any that I am not explicitly supporting.

**Comment by jasonspiro** [comment]
Thanks!  Closing.
