### ISSUE TITLE
where can i download the obb files?

### ISSUE THREAD

**Issue by yoke88** [corbinlc/GNURootDebian#20]
where can i download the obb files manully , because i can not download the obb files in china.

**Comment by yoke88** [comment]
using website like apkpure (which can download APK from google play,especially it can download APKX file, APKX file was a zip file ,when you unzip it ,it contains apk file and obb files)

The url i have used http://apkpure.com/store/apps/details?id=com.gnuroot.debian

**Comment by corbinlc** [comment]
The obb files can also be found in the repository.
