### ISSUE TITLE
new process started in gnuroot debian which run as non root can not write files

### ISSUE THREAD

**Issue by yoke88** [corbinlc/GNURootDebian#22]
###### Here was the command result:
~~~ bash
pwd 
/home
~~~~

home directory just **root and 1028 group** can write
~~~ bash
ls -la / |grep home
drwxrwx---.   9   root 1028 4096 Sep 13 10:14 home
~~~

but ipython run at user with **userid 10127(which can not write /home folder)**

~~~ bash
ps aux|grep ipython
10127 31101 23.4 1.1 47940 30984 pts/12 S 14:33 0:04 /usr/bin/python /usr/local/bin/ipython notebook
~~~

when i change the ipython notebook root folder to /tmp , there was no problem when saving ipython notebook ,i have not encounter the issue when using Gnuroot Wheezy with fake root.

**Comment by yoke88** [comment]
i have resolved my problem after  compare launchProot file in Wheezy and Debian..

after modify the file at /support/launchProot which site /data/data/com.gnuroot.debian/support/launchProot

I have delete "-b XXXXXX/home:/home " in the proot command line, and my ipython notebook works

**Comment by yoke88** [comment]
the home directory which originally bind to /storage/emulated/0/GNURoot/home = /sdcard/GNURoot/home 


after changed the lanuchProot file ,now it bound to /data/com.gnuroot/debian/debian/home

**Comment by pellet** [comment]
thanks for this information... I also had trouble with python's write access... mine was crashing when using conan dependency manager in:
`shutil.py line 208 in copytree`
I tried changing the home directory option in the app's preferences menu but it seemed to not help or do anything?
After changing /storage/emulated/0/GNURoot/home to /data/com.gnuroot/debian/debian/home  in the /support/launchProot file it fixed it! 👍
