### ISSUE TITLE
Whats the root passwort?

### ISSUE THREAD

**Issue by HGHD-Developer** [corbinlc/GNURootDebian#257]
Hey,

This all is very powerful but i have an question, what is the stamdard root passwort? I Also search for the Server folder wehre is it? Ive found the home folder but not my created folders. Tanks for answers :D

**Comment by HGHD-Developer** [comment]
Oh i forgot to ask, how can i use the ssh console with this server? Thanks dir help :)

**Comment by likeabossTM** [comment]
hi HGHD-Developer, there are not pasword because you have to create it, 

run 

anyuser@anyuser:~$ sudo passwd

then it will ask for the password you wish, put it twice and keep it safe that is your root password

**Comment by HGHD-Developer** [comment]
Ah thanks, but i doenst need it anymore
