### ISSUE TITLE
Suggestion: Using Multistrap

### ISSUE THREAD

**Issue by ExtremeNerd** [corbinlc/GNURootDebian#262]
It seems like GnuRoot Debian is built with Buildroot. Still it takes hundreds of MBs of Space. What about using Multistrap instead?

**Comment by AdamMatthewLTM** [comment]
@ExtremeNerd ,

Thank you for filing this issue. GNURootDebian does take up a bit of space, however if I may recommend:

At the moment the developers have released a new beta application, UserLAnd, intended to be an update and fix of GNURootDebian. It may be found at https://github.com/CypherpunkArmory/UserLAnd on GitHub. It is still in beta development at the moment.

While the application itself is only a few MB in size, some of the requirements (including a downloaded filesystem) are a bit larger, somewhere between 20-30MB on average. Nevertheless I believe the entire installation is well under 200MB (I could be mistaken). If you'd like to take a look at the beta, please do so!

Please reply to this thread if you have any further questions or comments, and thanks so much,
-Adam
