### ISSUE TITLE
Is it possible to SSH into a dropbear server on GnuRoot Debian from Termux on the same phone?

### ISSUE THREAD

**Issue by coder123123** [corbinlc/GNURootDebian#266]
Is it possible to SSH into a dropbear server on GnuRoot Debian from Termux on the same phone?

Trying to SSH into a dropbear server on Gnuroot from Termux. Can it be done and if so how?

**Comment by coder123123** [comment]
Answering my own question: yes it worked on port 2022.

**Comment by sstt011** [comment]
@coder123123 Please close this now then.

**Comment by coder123123** [comment]
Closed. Thanks for feedback.
