### ISSUE TITLE
Shall I replace GNURoot Wheezy with GNURootDebian

### ISSUE THREAD

**Issue by mayureshw** [corbinlc/GNURootDebian#33]
I read that GNURootDebian is the future.

Before last release GNURootDebian wasn't working for me on Android 5.x, though now it has started working.

I have a fairly well set GNURoo WheezyX envrionment, though I think it won't receive as much attention in future.

Can the present release of GNURootDebian now be considered mature enough so that I can start using it removing GNURoot application altogether?

**Comment by mayureshw** [comment]
I realize, GNURootDebian, after installation does not seem to have several basic utilities in the base. E.g. there is no vi. apt-get seem to be not set as well (may be repos are not configured). All this worked smoothly with GNURoot Wheezy.

Or did I miss anything in the installation process?

**Comment by mayureshw** [comment]
Closed accidentally.

**Comment by corbinlc** [comment]
I think you just need to do apt-get update and then apt-get install should work for getting you the other things that you want.  Can you confirm?  But, yes, GNURoot Wheezy and WheezyX are going to go away.  This will take their place.

**Comment by mayureshw** [comment]
Thanks. I was missing apt-get update. On a device with some space I am keeping both wheexy-x and gnuroot debian though will start moving things to the latter slowly.

[SD card writability is biggest hurdle in doing anything serious with gnuroot, though. Would request earnestly to look into on priority.]
