### ISSUE TITLE
useradd says "Cannot open audit interface - aborting."

### ISSUE THREAD

**Issue by mayureshw** [corbinlc/GNURootDebian#39]
useradd was working fine on gnuroot wheezy.
In gnuroot debian it gives above error.

**Comment by mayureshw** [comment]
I realize, this error does not occur if I do useradd on the device itself. It occurs only if I open a terminal on another device over ssh.

**Comment by corbinlc** [comment]
I think with the latest version of GNURoot Debian (update your app and hit the "patch" button), that this should work.  Can you confirm?
