### ISSUE TITLE
Prompt before reinstalling once linux is installed.

### ISSUE THREAD

**Issue by ehatfield57** [corbinlc/GNURootDebian#4]
First off: Thank you!  This is GREAT!
And please: Could you add a prompt to the installation, once it's been installed, so you don't accidentally overwrite the linux fs you just spent hours getting just right. :-) [Not that I would be stupid enough to do that.... no, no, no]

**Comment by corbinlc** [comment]
Yes definitely.  I was asked to do this before on the older version of GNURoot (to be phased out over time) and I should have done this right away for GNURoot Debian.  Sorry, even though we both know this didn't effect you ;)

**Comment by corbinlc** [comment]
A new version is rolling out now (check in an hour or too), it provides a confirmation prompt before installing/reinstalling.  It also has an "apply patches" button that will allow you to take many changes without having to reinstall your whole rootfs.

**Comment by ehatfield57** [comment]
That's Wonderful.  I can't tell you (but I'll try) how much I'm enjoying
the Debian environment on my android machine (with no rooting).  It's
something I've wanted for quite a while.  Thank you Very much for making my
dream come true... and saving myself from blowing away the whole
environment with one foolish click. :-)
