### ISSUE TITLE
Error when trying to install openssh-client

### ISSUE THREAD

**Issue by lovenemesis** [corbinlc/GNURootDebian#5]
When trying to install openssh-client through apt-get, I got the following error:

“Cannot open audit interface - aborting”

As a result, the package cannot be installed.

The reported issue looks a lot like the one here: https://unix.stackexchange.com/questions/211320/groupadd-failure-cannot-open-audit-interface

My device is a Sony Xperia Z4 Tablet with 64bit Android 5.0.
Does it relate the kernel this device is using?

**Comment by corbinlc** [comment]
See https://github.com/corbinlc/GNURootDebian/issues/6
There is a new version rolling out now that fixes useradd and groupadd issues (give it 1 or 2 hours) to show up as an update for you.  After updating, you need to either with the "install/reinstall" button or the "apply patches" button.  Then this should work.

**Comment by lovenemesis** [comment]
Confirmed this issue is fixed in 0.2.6

Thanks a lot!
