### ISSUE TITLE
How can I give root privilege to this app?

### ISSUE THREAD

**Issue by KJTang** [corbinlc/GNURootDebian#51]
I wrote some code and I wanted to exec it, but I could't chmod exec privilege to a file on sdcard, so I pushed it in to /data/data/com.gnuroot.debian/debian/opt/ through another app which has root privilege. Then I tried to run it in debian, but I found debian can't get access to /data/, because it hadn't get root privilege. So I want to know how to give root privilege to debian?

**Comment by corbinlc** [comment]
If you pushed something to /data/data/com.gnuroot.debian/debian/opt/ you will see it as simple /opt/ in GNURoot.  You should see your file there.  

I have not yet made it possible for GNURoot to become real root user.

**Comment by KJTang** [comment]
thanks
