### ISSUE TITLE
pty allocation fail for sshd connection

### ISSUE THREAD

**Issue by jiang-qian** [corbinlc/GNURootDebian#53]
starting sshd works after changing the listening port to 2222 and set UsePrivilegeSeparation to yes.

However, after logging in, I cannot request a tty. I get error
PTY allocation request failed on channel 1

**Comment by tuomas2** [comment]
I'm getting this too. Using dropbear. I can run commands with ssh and use sftp, but not have normal ssh session due to this error.

It seems that /dev is completely unreadable:

ls: cannot open directory /dev: Permission denied

**Comment by tuomas2** [comment]
On my Samsung tablet (Android 5.0.2) I can read /dev but there too PTY allocation requests fail with ssh Also tried screen and tmux without success on both devices.

**Comment by Emmanuel-F** [comment]
Same here on my honor7 with android 5.0.2
Related with android 5 ?

**Comment by jiang-qian** [comment]
I can confirm that this works! This is great, because now I am not
constricted to working on the tiny little screen and I can log in from my
laptop to do maintenance on the GNURoot installation! Thank you indeed for
that!
