### ISSUE TITLE
Cannot add user

### ISSUE THREAD

**Issue by cycojesus** [corbinlc/GNURootDebian#6]
adduser command fails as illustrated here:

    root@localhost:/# adduser test
    Adding user `test' ...
    Adding new group `test' (1000) ...
    Cannot open audit interface - aborting.
    adduser: `/usr/sbin/groupadd -g 1000 test' returned error code 1. Exiting.

**Comment by KDPRoss** [comment]
I'm having a similar problem: Here's the info that I'd sent Corbin:

Specifically, I cannot create a non‘root’ user; here's
what I've done:

- Installed GNURoot Debian via the Play store.

- Tapped ‘Install/Reinstall’; waited until the image was
  decompressed, which apparently completed successfully.

- Tapped ‘Launch’, which started a ‘root’ prompt.

- Ran ‘apt-get update && apt-get upgrade’:

  - (it upgraded ‘tzdata’ only)

- Tried to add a non‘root’ user:

  - ‘useradd -D myuser’; received this error: ‘Cannot open
    audit interface - aborting.’

- ‘/proc’ appears to be populated, ‘/sys’ is empty, and I
  get ‘Permission denied’ when I try to ‘ls /dev’ … FWIW.

Machine details:

- Device: Asus Memo K013

- Android 5, kernel 3.10.20-x86_64_byt build number
  LRX21V.WW_K013-12.10.1-24-20150623

**Comment by corbinlc** [comment]
A new version is rolling out now (wait an hour or two and it should be there).  It fixes this issue.  You will either need to hit the reinstall button or the apply patches button to get the fix.

**Comment by peterwilli** [comment]
@corbinlc could you tell me what the fix is? I have the same issue with proot and a ubuntu rootfs.
