### ISSUE TITLE
Unable to copy from browser via clipboard

### ISSUE THREAD

**Issue by gattila** [corbinlc/GNURootDebian#7]
If the content of the clipboard is not plain text, the paste menu item in the terminal is disabled. We need to copy the text from the browser to a text editor, then copy from it to the clipboard before we can  paste a text to the terminal. With the prior version of GNURoot we can copy a text from the browser and paste to gnuroot directly.

**Comment by corbinlc** [comment]
I see that there was a commit to the Terminal Emulator for Android project after I forked from it that says that it improves copy and paste functionality.  I will pick this commit up in the future and we can see if it makes things better.

**Comment by Manifold0** [comment]
Any progress or thoughts here? I'm definitely running into this issue, but I just found this project, so I haven't had a chance to delve into it, yet.

**Comment by corbinlc** [comment]
This should be fixed in version 0.6.11 the latest in the Play Store.  Can you confirm?

**Comment by memellis** [comment]
I'm on Marshmellow with a Note 4. How do I test.
I copied some text into the clipboard but don't how to paste.

**Comment by cdrasmussen** [comment]
Hold your finger a little too the right of where the cursor should be (it's
OK to guess) for about half a second and a pop-up menu will appear with a
pick for paste.

+CDR

**Comment by cdrasmussen** [comment]
Sorry to bother you but I've lost the msg which said where to get the most
recent image.

+CDR

On Apr 11, 2017 3:02 PM, "corbinlc" <notifications@github.com> wrote:

Closed #7 <https://github.com/corbinlc/GNURootDebian/issues/7>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/corbinlc/GNURootDebian/issues/7#event-1038923352>, or mute
the thread

**Comment by cdrasmussen** [comment]
I don't know when you will update the release but I'd like to start using
the recent fixes.

+CDR

**Comment by Manifold0** [comment]
Update should just be the latest version in the Google Play Store. Can you check your version number?

If you open your Android > Settings > Apps and find GNURoot Debian in the list, then open that, then you should see a version number. I'm running the latest from the play store and it's

version 0.6.12_armhf

**Comment by cdrasmussen** [comment]
Thanks. That's what I'm running. I misunderstood. I thought I saw a msg
about side loading a beta version from the dev site.

I'll patiently wait for the next release.

Is there a step by step for making a dev environment so I can work on the
bug list?

+CDR

**Comment by Manifold0** [comment]
You're going to want to use a combination of this:

https://developer.android.com/studio/install.html

And the README file from the app itself.
