### ISSUE TITLE
apt-get update does not work, seems to not connect to internet

### ISSUE THREAD

**Issue by sductor** [corbinlc/GNURootDebian#98]
First of all thank you for the work.

I succeed in installing but, I can not install anything from the terminal after.
apt-get update could not resolve/failed to fetch the source repositories.
I do not have access to ping or tracepath. I don't know how to check if interet is working. 
Hwever I obserevd the same behavior in gnuroot (not debian) and ping there could not reach google.

**Comment by tomaklutfu** [comment]
If you're behind a proxy, DNS set by `/etc/resolve.conf` happens to be the source of the failure. Add your proxy dns to that file. Doing `cat /etc/resolve.conf` will reveal what DNS IPs in use. It was `8.8.8.8` for me before I changed it.

**Comment by sductor** [comment]
Bam!!! Does the trick Thank you very much!!
For information, here is the procedure:
Install «Network Info II»
On the tab «Wifi» you will find the dns server in use.
Then on a terminal of GnuRoot enter:

mv /etc/resolve.conf /etc/resolve.conf-backup
cat >> /etc/resolve.conf
hit enter and write 
"nameserver your.local.ns.number1"
write one line for each
end with enter (new line)
and CTRL-D to close cat

You're done.
You can try to download 'ping' to see if internet works! ;)

**Comment by TheGuywithTheHat** [comment]
I found my DNS on windows with `ipconfig /all`

```
Ethernet adapter Ethernet:
   [REDACTED]
   DNS Servers . . . . . . . . . . . : 123.45.6.789
                                       123.45.6.780
   [REDACTED]
```
